### ISSUE TITLE
Cannot Run Example Code in Documentation: mprw.run_model() Path Error

### ISSUE THREAD

**Issue by nportilloda** [upc-ghs/flopyrw#1]
Hi! I’m trying to run the example provided in the documentation, but I’m encountering an error when I call mprw.run_model():

```
mprw.run_model()
Traceback (most recent call last):

  Cell In[24], line 1
    mprw.run_model()

  File /opt/anaconda3/lib/python3.9/site-packages/flopyrw/modpathrw/mprw.py:322 in run_model
    return run_model(

  File /opt/anaconda3/lib/python3.9/site-packages/flopyrw/modpathrw/mprw.py:407 in run_model
    raise ValueError(f"An executable name or path must be provided")
```

I’ve tried manually adding the path to the mp7 executable, but it still doesn’t resolve the issue. Could you provide any insights into what might be happening?

System details:
	•	OS: macOS 15.0.1
	•	Environment: Spyder v5.5.1
	•	Python Version: 3.9.7

Thanks in advance for the help!

**Comment by rodrperezi** [comment]
Hi, when you say "manually adding the path to the mp7 executable", are you refering to the ```exe_name``` argument in your declaration of ```mprw```,  like this ?
```
from flopyrw  import modpathrw

# Create a modpathrw model
# By default executable is 'mpathrw'
mprw = modpathrw.ModpathRW(flowmodel=gwf, exe_name="/path/to/exe")
```
In general giving the ```exe_name``` argument should solve the issue, just be sure to define ```exe_name``` with the path to a ```mpathrw``` executable. If ```exe_name``` is not given, then ```run_model``` assumes that the executable ```mpathrw``` is available at the same level than the python code, or through a symbolic link available at the system PATH pointing to an executable.

Which version of flopyrw are you using ?

**Comment by nportilloda** [comment]
Hi! Thanks for the help, it is now working. It was a problem with the version of gfortran I was using to generate the mpathrw exe.
